name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: pypi

    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build package
        run: hatch build

      - name: Run tests with Hatch
        run: hatch test

      - name: Publish package distributions to PyPI
        run: pypa/gh-action-pypi-publish@release/v1
